from langchain_openai import ChatOpenAI
from dotenv import load_dotenv
from langchain_core.prompts import PromptTemplate
import os
from langchain_core.output_parsers import StrOutputParser

load_dotenv()  # Loads environment variables so API credentials can be accessed securely.

model = ChatOpenAI(
    model='mistralai/Mistral-Small-3.1-24B-Instruct-2503',
    api_key=os.getenv("LLM_API_KEY"),     # Retrieves API key from environment variables.
    base_url=os.getenv("LLM_BASE_URL")    # Reads custom endpoint if configured.
)

# ---------------- FIRST PROMPT ----------------
# PromptTemplate dynamically inserts values at runtime.
# {topic} will be replaced when the chain is executed.
# This prompt generates detailed content which becomes
# the input for the next step.
template1 = PromptTemplate(
    template="write a detailed report on the {topic}",
    input_variables=['topic']
)

# ---------------- SECOND PROMPT ----------------
# Receives output from the previous step automatically.
# {content} placeholder will contain the detailed report
# generated by the first model call.
template2 = PromptTemplate(
    template="write the content in 3 lines summary {content}",
    input_variables=['content']
)

# ---------------- STRING OUTPUT PARSER ----------------
# StrOutputParser extracts only the text content from
# the LLM response object.
# LLM responses contain metadata + message structure;
# this parser converts them into a clean string so that
# the next component can directly use the output.
outputparser = StrOutputParser()

# ---------------- CHAIN PIPELINE ----------------
# "|" operator connects components into a sequential workflow.
#
# Execution flow:
# 1. template1 formats prompt using provided topic.
# 2. model generates detailed report.
# 3. parser converts response into plain string.
# 4. template2 injects that string as {content}.
# 5. model generates 3-line summary.
# 6. parser extracts final clean text output.
#
# Benefits of using chains:
# - Automatic passing of outputs between steps
# - No manual extraction or variable handling
# - Cleaner and scalable multi-step LLM workflows
# - Easy debugging and extension later
chain = template1 | model | outputparser | template2 | model | outputparser

# ---------------- EXECUTION ----------------
# invoke():
# Runs the entire pipeline once.
# Replaces {topic} with input value and processes
# data through every step automatically.
result = chain.invoke({'topic': 'black hole'})

# Final output is already a clean string summary.
print(result)